# Generated by Django 4.2 on 2023-04-14 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.CharField(max_length=50, verbose_name='Išrašymo data')),
                ('ammount_of_money', models.CharField(max_length=50, verbose_name='Suma')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50, verbose_name='Pavadinimas')),
                ('job_note', models.CharField(max_length=50, verbose_name='Pastabos')),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klient_name', models.CharField(max_length=50, verbose_name='Vardas')),
                ('klient_last_name', models.CharField(max_length=50, verbose_name='Pavarde')),
                ('klient_firm', models.CharField(max_length=50, verbose_name='Imone')),
                ('klient_kontacts', models.CharField(max_length=50, verbose_name='kontaktai')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=50, verbose_name='Vardas')),
                ('worker_last_name', models.CharField(max_length=50, verbose_name='Pavarde')),
                ('worker_duty', models.CharField(max_length=50, verbose_name='Pareigos')),
            ],
        ),
        migrations.CreateModel(
            name='Projektas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Pavadinimas')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngc.account')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngc.job')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngc.klient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngc.worker')),
            ],
        ),
    ]
