# Generated by Django 4.2 on 2023-04-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Saskaita', 'verbose_name_plural': 'Saskaitos'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Darbas', 'verbose_name_plural': 'Darbai'},
        ),
        migrations.AlterModelOptions(
            name='klient',
            options={'verbose_name': 'Klientas', 'verbose_name_plural': 'Klientai'},
        ),
        migrations.AlterModelOptions(
            name='projektas',
            options={'verbose_name': 'Projektas', 'verbose_name_plural': 'Projektai'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Darbuotojas', 'verbose_name_plural': 'Darbuotojai'},
        ),
    ]
