# Generated by Django 4.2 on 2023-04-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngc', '0004_alter_projektas_accounts_alter_projektas_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='klient_kontacts',
            field=models.CharField(max_length=50, verbose_name='Kontaktai'),
        ),
    ]
