# Generated by Django 4.2 on 2023-04-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngc', '0005_alter_klient_klient_kontacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projektas',
            name='klient',
        ),
        migrations.AddField(
            model_name='projektas',
            name='klient',
            field=models.ManyToManyField(to='ngc.klient'),
        ),
    ]
